"""Generate acceptance tests for features.

When a feature is implemented, acceptance tests verify that the implementation
matches the desired outcome. Tests are generated from the feature request and
run as part of the PR verification pipeline.

Tests should be:
- Deterministic: same input always produces same result
- Fast: run in seconds, not minutes
- Focused: test one feature aspect, not the whole system
- Readable: test logic is obvious from the code
- Maintainable: changes to implementation don't break test structure
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional

from openjarvis.wiz.features.model import FeatureRequest

logger = logging.getLogger(__name__)

__all__ = ["TestType", "AcceptanceTest", "AcceptanceTestSuite"]


class TestType(str, Enum):
    """What kind of test."""

    UNIT = "unit"  # test isolated function/class
    INTEGRATION = "integration"  # test feature interaction with system
    SMOKE = "smoke"  # quick sanity check
    REGRESSION = "regression"  # ensure old bugs don't come back
    PERFORMANCE = "performance"  # ensure feature is fast enough


@dataclass
class AcceptanceTest:
    """One test in an acceptance test suite."""

    name: str
    test_type: TestType
    description: str
    code: str  # the actual test code (pytest or similar)
    expected_result: str  # what should happen when test passes
    timeout_seconds: int = 30  # max time for test to run
    is_critical: bool = True  # must pass for feature to merge
    tags: List[str] = None  # e.g., ["fast", "no-external-services"]

    def __post_init__(self) -> None:
        if self.tags is None:
            self.tags = []

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "test_type": self.test_type.value,
            "description": self.description,
            "code": self.code,
            "expected_result": self.expected_result,
            "timeout_seconds": self.timeout_seconds,
            "is_critical": self.is_critical,
            "tags": self.tags,
        }


@dataclass
class AcceptanceTestSuite:
    """Collection of acceptance tests for a feature."""

    feature_id: str
    tests: List[AcceptanceTest]

    def critical_tests(self) -> List[AcceptanceTest]:
        """Tests that must pass for feature approval."""
        return [t for t in self.tests if t.is_critical]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "feature_id": self.feature_id,
            "tests": [t.to_dict() for t in self.tests],
            "critical_count": len(self.critical_tests()),
            "total_count": len(self.tests),
        }


class AcceptanceTestGenerator:
    """Generate acceptance tests from feature requests.

    Tests are generated by analyzing:
    - Feature title and description
    - Desired outcome
    - Risk level (higher risk = more tests)
    - Feature type (new feature, bug fix, refactor)

    Generated tests are templates that Claude Code sessions will enhance
    and make concrete as they implement the feature.
    """

    def generate(self, feature: FeatureRequest) -> AcceptanceTestSuite:
        """Generate acceptance tests for a feature."""
        tests: List[AcceptanceTest] = []

        # Analyze feature to determine what tests are needed
        feature_type = self._classify_feature(feature)
        risk_level = self._risk_level(feature)

        # Generate core test based on feature type
        if feature_type == "new_feature":
            tests.extend(self._tests_for_new_feature(feature, risk_level))
        elif feature_type == "bug_fix":
            tests.extend(self._tests_for_bug_fix(feature, risk_level))
        elif feature_type == "refactor":
            tests.extend(self._tests_for_refactor(feature, risk_level))

        # Add regression tests for high-risk changes
        if risk_level == "HIGH":
            tests.append(self._make_regression_test(feature))

        # Sort by criticality (critical tests first)
        tests.sort(key=lambda t: (not t.is_critical, t.name))

        return AcceptanceTestSuite(feature_id=feature.id, tests=tests)

    def _classify_feature(self, feature: FeatureRequest) -> str:
        """Classify feature type from request."""
        title_lower = (feature.title or "").lower()
        request_lower = (feature.operator_request or "").lower()
        text = title_lower + " " + request_lower

        if any(word in text for word in ["fix", "bug", "error", "crash"]):
            return "bug_fix"
        if any(word in text for word in ["refactor", "reorganize", "restructure"]):
            return "refactor"
        return "new_feature"

    def _risk_level(self, feature: FeatureRequest) -> str:
        """Determine risk level."""
        if feature.risk and feature.risk.upper() == "CRITICAL":
            return "HIGH"
        if feature.risk and feature.risk.upper() in ("HIGH", "MEDIUM"):
            return "MEDIUM"
        return "LOW"

    def _tests_for_new_feature(
        self, feature: FeatureRequest, risk_level: str
    ) -> List[AcceptanceTest]:
        """Generate tests for a new feature."""
        tests: List[AcceptanceTest] = []

        # Test 1: Feature exists and is accessible
        tests.append(
            AcceptanceTest(
                name="test_feature_exists",
                test_type=TestType.UNIT,
                description=f"Verify that {feature.title} is implemented",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_exists():
    # Verify the feature or function exists
    # Example: from module import new_feature
    # Example: assert callable(new_feature)
    # TODO: Implement actual test
    pass
""",
                expected_result="Feature is importable and callable",
                is_critical=True,
            )
        )

        # Test 2: Feature works with valid input
        tests.append(
            AcceptanceTest(
                name="test_feature_valid_input",
                test_type=TestType.UNIT,
                description="Feature works correctly with valid input",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_valid():
    # Test with valid input
    # TODO: Implement actual test
    result = None  # call feature with valid input
    assert result is not None
""",
                expected_result="Feature returns expected result",
                is_critical=True,
            )
        )

        # Test 3: Feature handles invalid input gracefully
        tests.append(
            AcceptanceTest(
                name="test_feature_invalid_input",
                test_type=TestType.UNIT,
                description="Feature handles invalid input gracefully",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_invalid():
    # Test with invalid input
    # TODO: Implement actual test
    with pytest.raises((ValueError, TypeError)):
        pass  # call feature with invalid input
""",
                expected_result="Feature raises appropriate exception",
                is_critical=risk_level == "HIGH",
            )
        )

        # Test 4: Feature meets desired outcome (if risk is high)
        if risk_level == "HIGH":
            tests.append(
                AcceptanceTest(
                    name="test_feature_outcome",
                    test_type=TestType.INTEGRATION,
                    description="Feature achieves desired outcome",
                    code=f"""
def test_{feature.id.lower().replace('-', '_')}_outcome():
    # Test that the feature achieves its desired outcome:
    # {feature.desired_outcome}
    # TODO: Implement actual test
    pass
""",
                    expected_result="Desired outcome is achieved",
                    is_critical=True,
                    timeout_seconds=60,
                )
            )

        return tests

    def _tests_for_bug_fix(
        self, feature: FeatureRequest, risk_level: str
    ) -> List[AcceptanceTest]:
        """Generate tests for a bug fix."""
        tests: List[AcceptanceTest] = []

        # Test 1: Bug is fixed (reproduce and verify fix)
        tests.append(
            AcceptanceTest(
                name="test_bug_fixed",
                test_type=TestType.UNIT,
                description=f"Verify that the bug is fixed: {feature.title}",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_fixed():
    # This test should have failed before the fix and pass after
    # Reproduce the original bug condition
    # TODO: Implement test that demonstrates the bug is fixed
    pass
""",
                expected_result="Bug no longer occurs",
                is_critical=True,
            )
        )

        # Test 2: Fix doesn't introduce regression
        tests.append(
            AcceptanceTest(
                name="test_no_regression",
                test_type=TestType.REGRESSION,
                description="Fix doesn't break related functionality",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_no_regression():
    # Ensure related functionality still works
    # TODO: Implement regression test
    pass
""",
                expected_result="Related functionality is unaffected",
                is_critical=True,
            )
        )

        return tests

    def _tests_for_refactor(
        self, feature: FeatureRequest, risk_level: str
    ) -> List[AcceptanceTest]:
        """Generate tests for a refactor."""
        tests: List[AcceptanceTest] = []

        # Test 1: Behavior is unchanged
        tests.append(
            AcceptanceTest(
                name="test_behavior_unchanged",
                test_type=TestType.SMOKE,
                description=f"Refactored code has same behavior: {feature.title}",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_behavior():
    # Test that the public API/behavior is unchanged
    # TODO: Implement test
    pass
""",
                expected_result="Public behavior is identical",
                is_critical=True,
            )
        )

        # Test 2: Code quality improvements
        tests.append(
            AcceptanceTest(
                name="test_code_quality",
                test_type=TestType.SMOKE,
                description="Refactored code is more maintainable",
                code=f"""
def test_{feature.id.lower().replace('-', '_')}_quality():
    # Verify code quality improvements
    # Examples: reduced complexity, better naming, improved documentation
    # TODO: Implement test
    pass
""",
                expected_result="Code quality is improved",
                is_critical=False,
            )
        )

        return tests

    def _make_regression_test(
        self, feature: FeatureRequest
    ) -> AcceptanceTest:
        """Create a regression test for high-risk features."""
        return AcceptanceTest(
            name="test_regression_protection",
            test_type=TestType.REGRESSION,
            description=f"Regression protection for {feature.title}",
            code=f"""
def test_{feature.id.lower().replace('-', '_')}_regression():
    # This test ensures the bug/regression doesn't come back
    # This test should fail if the issue is re-introduced
    # TODO: Implement regression test
    pass
""",
            expected_result="Regression is prevented",
            is_critical=True,
        )
